/*******************************************************************************
 * Copyright (c) 2012 IBM Corporation and others.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * and Eclipse Distribution License v. 1.0 which accompanies this distribution.
 *
 * The Eclipse Public License is available at http://www.eclipse.org/legal/epl-v10.html
 * and the Eclipse Distribution License is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * Contributors:
 *
 *     Russell Boykin       - initial API and implementation
 *     Alberto Giammaria    - initial API and implementation
 *     Chris Peters         - initial API and implementation
 *     Gianluca Bernardini  - initial API and implementation
 *     Michael Fiedler      - Bugzilla adpater implementations
 *     Jad El-khoury        - initial implementation of code generator (https://bugs.eclipse.org/bugs/show_bug.cgi?id=422448)
 *
 * This file is generated by org.eclipse.lyo.oslc4j.codegenerator
 *******************************************************************************/

package hu.bme.mit.massif.oslc.adaptor;

// Start of user code imports
// End of user code

public interface SimulinkAdaptorConstants {
    // Start of user code user constants
    // End of user code

    public static String       SIMULINK_DOMAIN               = "http://hu.bme.mit.transima/simu/1.0/";
    public static String       SIMULINK_NAMSPACE             = "http://hu.bme.mit.transima/simu/1.0/";
    public static String       SIMULINK_NAMSPACE_PREFIX      = "simu";

    public static String       BLOCKRESOURCE                 = "blockResource";
    public static String       PATH_BLOCKRESOURCE            = "blockResource";
    public static String       TYPE_BLOCKRESOURCE            = SIMULINK_NAMSPACE + "BlockResource";
    public static String       BUSCREATORRESOURCE            = "busCreatorResource";
    public static String       PATH_BUSCREATORRESOURCE       = "busCreatorResource";
    public static String       TYPE_BUSCREATORRESOURCE       = SIMULINK_NAMSPACE + "BusCreatorResource";
    public static String       BUSSELECTORRESOURCE           = "busSelectorResource";
    public static String       PATH_BUSSELECTORRESOURCE      = "busSelectorResource";
    public static String       TYPE_BUSSELECTORRESOURCE      = SIMULINK_NAMSPACE + "BusSelectorResource";
    public static String       BUSSPECIFICATIONRESOURCE      = "busSpecificationResource";
    public static String       PATH_BUSSPECIFICATIONRESOURCE = "busSpecificationResource";
    public static String       TYPE_BUSSPECIFICATIONRESOURCE = SIMULINK_NAMSPACE + "BusSpecificationResource";
    public static String       ENABLEBLOCKRESOURCE           = "enableBlockResource";
    public static String       PATH_ENABLEBLOCKRESOURCE      = "enableBlockResource";
    public static String       TYPE_ENABLEBLOCKRESOURCE      = SIMULINK_NAMSPACE + "EnableBlockResource";
    public static String       ENABLERESOURCE                = "enableResource";
    public static String       PATH_ENABLERESOURCE           = "enableResource";
    public static String       TYPE_ENABLERESOURCE           = SIMULINK_NAMSPACE + "EnableResource";
    public static String       FROMRESOURCE                  = "fromResource";
    public static String       PATH_FROMRESOURCE             = "fromResource";
    public static String       TYPE_FROMRESOURCE             = SIMULINK_NAMSPACE + "FromResource";
    public static String       GOTORESOURCE                  = "gotoResource";
    public static String       PATH_GOTORESOURCE             = "gotoResource";
    public static String       TYPE_GOTORESOURCE             = SIMULINK_NAMSPACE + "GotoResource";
    public static String       INPORTBLOCKRESOURCE           = "inPortBlockResource";
    public static String       PATH_INPORTBLOCKRESOURCE      = "inPortBlockResource";
    public static String       TYPE_INPORTBLOCKRESOURCE      = SIMULINK_NAMSPACE + "InPortBlockResource";
    public static String       INPORTRESOURCE                = "inPortResource";
    public static String       PATH_INPORTRESOURCE           = "inPortResource";
    public static String       TYPE_INPORTRESOURCE           = SIMULINK_NAMSPACE + "InPortResource";
    public static String       OUTPORTBLOCKRESOURCE          = "outPortBlockResource";
    public static String       PATH_OUTPORTBLOCKRESOURCE     = "outPortBlockResource";
    public static String       TYPE_OUTPORTBLOCKRESOURCE     = SIMULINK_NAMSPACE + "OutPortBlockResource";
    public static String       OUTPORTRESOURCE               = "outPortResource";
    public static String       PATH_OUTPORTRESOURCE          = "outPortResource";
    public static String       TYPE_OUTPORTRESOURCE          = SIMULINK_NAMSPACE + "OutPortResource";
    public static String       PORTBLOCKRESOURCE             = "portBlockResource";
    public static String       PATH_PORTBLOCKRESOURCE        = "portBlockResource";
    public static String       TYPE_PORTBLOCKRESOURCE        = SIMULINK_NAMSPACE + "PortBlockResource";
    public static String       PORTRESOURCE                  = "portResource";
    public static String       PATH_PORTRESOURCE             = "portResource";
    public static String       TYPE_PORTRESOURCE             = SIMULINK_NAMSPACE + "PortResource";
    public static String       SIMULINKELEMENTRESOURCE       = "simulinkElementResource";
    public static String       PATH_SIMULINKELEMENTRESOURCE  = "simulinkElementResource";
    public static String       TYPE_SIMULINKELEMENTRESOURCE  = SIMULINK_NAMSPACE + "SimulinkElementResource";
    public static String       SIMULINKMODELRESOURCE         = "simulinkModelResource";
    public static String       PATH_SIMULINKMODELRESOURCE    = "simulinkModelResource";
    public static String       TYPE_SIMULINKMODELRESOURCE    = SIMULINK_NAMSPACE + "SimulinkModelResource";
    public static String       SUBSYSTEMRESOURCE             = "subSystemResource";
    public static String       PATH_SUBSYSTEMRESOURCE        = "subSystemResource";
    public static String       TYPE_SUBSYSTEMRESOURCE        = SIMULINK_NAMSPACE + "SubSystemResource";
    public static String       TRIGGERBLOCKRESOURCE          = "triggerBlockResource";
    public static String       PATH_TRIGGERBLOCKRESOURCE     = "triggerBlockResource";
    public static String       TYPE_TRIGGERBLOCKRESOURCE     = SIMULINK_NAMSPACE + "TriggerBlockResource";
    public static String       TRIGGERRESOURCE               = "triggerResource";
    public static String       PATH_TRIGGERRESOURCE          = "triggerResource";
    public static String       TYPE_TRIGGERRESOURCE          = SIMULINK_NAMSPACE + "TriggerResource";
    public static String       VIRTUALBLOCKRESOURCE          = "virtualBlockResource";
    public static String       PATH_VIRTUALBLOCKRESOURCE     = "virtualBlockResource";
    public static String       TYPE_VIRTUALBLOCKRESOURCE     = SIMULINK_NAMSPACE + "VirtualBlockResource";

    public static final String HDR_OSLC_VERSION              = "OSLC-Core-Version";

}
