<!DOCTYPE html>
<%--
 Copyright (c) 2011, 2012 IBM Corporation and others.

 All rights reserved. This program and the accompanying materials
 are made available under the terms of the Eclipse Public License v1.0
 and Eclipse Distribution License v. 1.0 which accompanies this distribution.
 
 The Eclipse Public License is available at http://www.eclipse.org/legal/epl-v10.html
 and the Eclipse Distribution License is available at
 http://www.eclipse.org/org/documents/edl-v10.php.
 
 Contributors:
 
    Sam Padgett 	 - initial API and implementation
    Michael Fiedler	 - adapted for OSLC4J
	Jad El-khoury        - initial implementation of code generator (https://bugs.eclipse.org/bugs/show_bug.cgi?id=422448)

 This file is generated by org.eclipse.lyo.oslc4j.codegenerator
--%>

<%@page import="hu.bme.mit.massif.oslc.adaptor.resources.SubSystemResource" %>
<%--
Start of user code imports
--%>
<%-- 
End of user code 
--%>


<%@ page contentType="text/html" language="java" pageEncoding="UTF-8" %>

<%
    String serviceProviderId = (String) request.getAttribute("serviceProviderId");
%>
<%--
Start of user code getRequestAttributes
--%>
<%--
End of user code
--%>

<html>
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8">
    <title>Resource Creator</title>
    <%--
Start of user code (RECOMMENDED) headStuff 
    --%>
    <%--
End of user code 
    --%>
</head>
<body style="padding: 10px;">
<div id="bugzilla-body">
    <form id="Create" method="POST" class="enter_bug_form">
        <%--
Start of user code (RECOMMENDED) formStuff 
        --%>
        <%--
End of user code 
        --%>
        <table style="clear: both;">

            <tr>
                <td><%= SubSystemResource.sourceBlockToHtmlForCreation(request, serviceProviderId)%>
                </td>
            </tr>
            <tr>
                <td><%= SubSystemResource.triggerToHtmlForCreation(request, serviceProviderId)%>
                </td>
            </tr>
            <tr>
                <td><%= SubSystemResource.portssToHtmlForCreation(request, serviceProviderId)%>
                </td>
            </tr>
            <tr>
                <td><%= SubSystemResource.subBlockssToHtmlForCreation(request, serviceProviderId)%>
                </td>
            </tr>
            <tr>
                <td><%= SubSystemResource.propertysToHtmlForCreation(request, serviceProviderId)%>
                </td>
            </tr>
            <tr>
                <td><%= SubSystemResource.inportssToHtmlForCreation(request, serviceProviderId)%>
                </td>
            </tr>
            <tr>
                <td><%= SubSystemResource.tagToHtmlForCreation(request, serviceProviderId)%>
                </td>
            </tr>
            <tr>
                <td><%= SubSystemResource.parentToHtmlForCreation(request, serviceProviderId)%>
                </td>
            </tr>
            <tr>
                <td><%= SubSystemResource.nameToHtmlForCreation(request, serviceProviderId)%>
                </td>
            </tr>
            <tr>
                <td><%= SubSystemResource.enablerToHtmlForCreation(request, serviceProviderId)%>
                </td>
            </tr>
            <tr>
                <td><%= SubSystemResource.outportssToHtmlForCreation(request, serviceProviderId)%>
                </td>
            </tr>
            <tr>
                <td><%= SubSystemResource.simulinkRefToHtmlForCreation(request, serviceProviderId)%>
                </td>
            </tr>


            <tr>
                <td></td>
                <td>
                    <input type="submit" value="Submit">
                    <input type="reset">
                </td>
            </tr>
        </table>


        <div style="width: 500px;">

        </div>

    </form>

    <div style="clear: both;"></div>
</div>
</body>
</html>



