= Headless usage of Massif in MATLAB IDE

The CLI package of Massif allows the converting between the Simulink models and Massif EMF models inside of MATLAB scripts.

== Setup

Download the package from: 

* https://static.incquerylabs.com/projects/massif/release/0.7.0/hu.bme.mit.massif.simulink.cli-example-0.7.0.zip[Version 0.7 (Latest release)]
* https://build.incquerylabs.com/nexus/service/rest/v1/search/assets/download?sort=version&repository=massif-snapshots&maven.groupId=hu.bme.mit.massif.features&maven.artifactId=hu.bme.mit.massif.simulink.cli-package&maven.baseVersion=0.8.0-SNAPSHOT&maven.classifier=massif-cli&maven.extension=zip[Latest build (CI)]

You have to download it and add its path to the MATLAB's java path via the `javaaddpath(/*jar's location as a string goes here*/)` command.

== Create MATLAB model from Massif EMF model

First you have to create a `modelImporter` object which is an instance of the CLIMatlabCreator class:
[source, MATLAB]
----
modelImporter = hu.bme.mit.massif.simulink.cli.CLIMatlabCreator;
----
With this you can create the MATLAB model via calling CLIMatlabCreator's `createMatlabModel()` method like this:
[source, MATLAB]
----
modelImporter.createMatlabModel([modelName], [modelPath], [extension - optional]);
----
** The `modelName` is the name of the model file without extension as a string.
** The `modelPath` is the folder path containing the model file as a string.
** The (optional) `extension` is the file extension in which the created model file will be saved.
Its default is `"slx"`.

== Create Massif EMF model from MATLAB model

First you have to create a `modelExporter` object which is an instance of the CLIEMFCreator class:
[source, MATLAB]
----
modelExporter = hu.bme.mit.massif.simulink.cli.CLIEMFCreator;
----
With this you can create the Massif EMF model via calling CLIEMFCreator's `createSimulinkModel()` method like this:
[source, MATLAB]
----
modelExporter.createSimulinkModel([modelName], [outputDir], [importMode - optional]);
----
** The `modelName` is the name of the model file without extension as a string.
** The `outputDir` is the folder path in which the generated Massif EMF model will be saved.
** The (optional) `importMode` is an enum to select the import mode.
It can have the following four values:
*** `hu.bme.mit.massif.simulink.api.util.ImportMode.SHALLOW`
*** `hu.bme.mit.massif.simulink.api.util.ImportMode.DEEP`
*** `hu.bme.mit.massif.simulink.api.util.ImportMode.FLATTENING`
*** `hu.bme.mit.massif.simulink.api.util.ImportMode.REFERENCING`
+
The meaning of the import modes is described <<eclipse_overView#traverse_mode, here>>.